[package]
name = "game"
version = "0.1.1"
edition = "2024"

[dependencies]
piston = "1.0.0"
piston2d-graphics = "0.45.0"
pistoncore-glutin_window = "0.73.2"
piston2d-opengl_graphics = "0.89.0"
polars = { version = "0.53.0", features = ["lazy", "csv", "rows", "strings", "regex"]}
approx = "0.5.1"
rusttype = "0.9.3"
